language: go
go:
  - "1.x"
  - "1.9.x"
  - "1.10.x"
  - "master"

sudo: false

install:
  - go get -v -t ./...
script:
  - source ./.travis/script
after_success:
  - source ./.travis/after_success

env:
  global:
    # GITHUB_TOKEN for automatic releases
    - secure: "at1oJs7ib7glx3W+zk+OkT041LdknVXirIhN403CIihVUrlOhODY7yCTgvF4Rk0jYBJiT35Q2qxpgfWF2qGnsNsQmjG3ydDWQDCepDc/CgXfLyoiSTJK5vTK72dYWTVsBTycXbj1CbSy2X2ah/KWjc4RcgZ67ER7mDpRU5nFeow="
    # Set this to the Go version to use for releases (must appear in version list above).
    - RELEASE_GO_VERSION="1.10"
